title: CTRL+HACK+DEL Documentation
description: The 2025 documentation on how to build CTRL+HACK+DEL efficiently and effectively.
theme: just-the-docs

url: https://ctrlhackdel.github.io

aux_links:
  "CTRL+HACK+DEL Website": https://ctrlhackdel.com

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"