title: CTRL+HACK+DEL Documentation
description: The 2025 documentation on how to build CTRL+HACK+DEL efficiently and effectively.
theme: just-the-docs

url: https://ctrlhackdel.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
